/**************************************************************************** 
 * Job:             meh_dm.pledge                         A5M8HTKH.BO0000YA * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: 217.29.235.142                                          * 
 * Port:            8563                                                    * 
 * Location:        /dw_solution/meh/programs/jobs                          * 
 *                                                                          * 
 * Server:          SASApp                                A5M8HTKH.AS000002 * 
 *                                                                          * 
 * Source Table:    dwh_dw.ACCOUNT_COLLATERAL_LINK        A5M8HTKH.BB0002SJ * 
 * Target Table:    meh_dm.PLEDGE                         A5M8HTKH.BB0002M8 * 
 *                                                                          * 
 * Generated on:    den 22 december 2021 kl 14:59 EET                       * 
 * Generated by:    amattsso                                                * 
 * Version:         SAS Data Integration Studio 4.904                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5M8HTKH.BO0000YA);
%let etls_jobName = %nrquote(meh_dm.pledge);
%let etls_userID = %nrquote(amattsso);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */ 
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

%preprocess_std;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0005V6 * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dwh_dw.ACCOUNT_COLLATERAL_LINK        A5M8HTKH.BB0002SJ * 
 * Target Table:    shadow_OUTPUT0 - work.W4RCYXC         A5M8HTKH.BR0004CD * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0005V6);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dwh_dw.ACCOUNT_COLLATERAL_LINK); 

%let _INPUT_count = 1; 
%let _INPUT = dwh_dw.ACCOUNT_COLLATERAL_LINK;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(&altercommand.);
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/dw_solution/dwh/data/dw/dwh_dw.ACCOUNT_COLLATERAL_LINK%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = dwh_dw.ACCOUNT_COLLATERAL_LINK;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(&altercommand.);
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/dw_solution/dwh/data/dw/dwh_dw.ACCOUNT_COLLATERAL_LINK%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.W4RCYXC;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR0004CD%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id internal_collateral_id 
        internal_pledge_id source_system_cd extracted_dt loaded_dt;

%let _OUTPUT0 = work.W4RCYXC;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR0004CD%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id internal_collateral_id 
        internal_pledge_id source_system_cd extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete W4RCYXC;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id internal_collateral_id 
        internal_pledge_id source_system_cd extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id internal_collateral_id 
        internal_pledge_id source_system_cd extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end shadow **/

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU0005V5 * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    shadow_OUTPUT0 - work.W4RCYXC         A5M8HTKH.BR0004CD * 
 * Target Table:    Extract - work.W4LL8ZX                A5M8HTKH.BR0004CB * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0005V5);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W4RCYXC); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W4LL8ZX;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W4LL8ZX as
      select distinct
         information_date   
            informat = DDMMYY10.,
         bank_id   
            label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
         internal_pledge_id   
            label = 'CBS internal pledge ID related to the Account and the Collateral',
         (input( substr(internal_pledge_id,2),Best8.)) as pledge_number length = 4
            format = 10.
            label = 'Pledge number (numeric part of the internal pledge ID)',
         (case when substr(internal_pledge_id,1,1)='S' then 'PLEDGE'  when substr(internal_pledge_id,1,1)='G' then 'GENERAL_PLEDGE' end) as pledge_type_cd length = 20
            label = 'Pledge type (GENERAL_PLEDGE, GENERAL_GUARANTEE, PLEDGE, GUARANTEE)',
         ('') as limit_currency_cd length = 3
            label = 'Pledge limit currency code',
         (0) as limit_amt length = 8
            format = 15.2
            label = 'Pledge limit amount in limit currency',
         (.) as complementary_pledge_flag length = 3
            format = 3.
            label = 'Pledge regarded as complementary: 1=Yes, 0=No, .=unknown',
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = DATETIME20.
            label = 'Load timestamp (date & time)'
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W4LL8ZX;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract **/

/*==========================================================================* 
 * Step:            history                               A5M8HTKH.BU0003IZ * 
 * Transform:       history                                                 * 
 * Description:     Executes history management on connected table          * 
 *                                                                          * 
 * Source Table:    Extract - work.W4LL8ZX                A5M8HTKH.BR0004CB * 
 * Target Table:    meh_dm.PLEDGE                         A5M8HTKH.BB0002M8 * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0003IZ);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W4LL8ZX); 

%let _INPUT_count = 1; 
%let _INPUT = work.W4LL8ZX;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = VIEW;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Extract_A5M8HTKH.BR0004CB%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.W4LL8ZX;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = VIEW;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/Extract_A5M8HTKH.BR0004CB%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = meh_dm.PLEDGE;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT_path = %nrquote(/dw_solution/meh/data/dm/meh_dm.PLEDGE%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote(Pledge data mart table);
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id internal_pledge_id pledge_number 
        pledge_type_cd limit_currency_cd limit_amt complementary_pledge_flag 
        loaded_dt;

%let _OUTPUT0 = meh_dm.PLEDGE;
%let _OUTPUT0_connect = null;
%let _OUTPUT0_engine = BASE;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_path = %nrquote(/dw_solution/meh/data/dm/meh_dm.PLEDGE%(Table%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote(Pledge data mart table);
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id internal_pledge_id pledge_number 
        pledge_type_cd limit_currency_cd limit_amt complementary_pledge_flag 
        loaded_dt;


%let dimfields = ;
%let dimfields_count = 0;
%let dimfields0 = 0;
%let dimfields = ;

/* List of target columns to keep  */ 
%let _keep = information_date bank_id internal_pledge_id pledge_number 
        pledge_type_cd limit_currency_cd limit_amt complementary_pledge_flag 
        loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id internal_pledge_id pledge_number 
        pledge_type_cd limit_currency_cd limit_amt complementary_pledge_flag 
        loaded_dt;
%history(source=&_INPUT0.,target=&_OUTPUT0.,metapath=&_OUTPUT0_path.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

/*---- Create the indexes for a table  ----*/ 
%put %str(NOTE: Creating indexes ...);
proc datasets lib = meh_dm nolist; 
   modify PLEDGE(&altercommand. ); 
      index create primary_index = (information_date bank_id internal_pledge_id pledge_number)
         / unique;
quit; 

%rcSet(&syserr); 



/** Step end history **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/*---- Start of Post-Process Code  ----*/ 

%postprocess_std;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

