/**************************************************************************** 
 * Job:             meh_resu.ecl_obl                      A5M8HTKH.BO000255 * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: 217.29.235.142                                          * 
 * Port:            8561                                                    * 
 * Location:        /dw_solution/meh/programs/jobs                          * 
 *                                                                          * 
 * Server:          SASApp                                A5M8HTKH.AS000002 * 
 *                                                                          * 
 * Source Table:    meh_isar.ECL_OBL - meh_isar.ecl_obl   A5M8HTKH.BB000470 * 
 * Target Table:    meh_resu.ECL_OBL                      A5M8HTKH.BB000471 * 
 *                                                                          * 
 * Generated on:    Monday, April 11, 2022 5:04:38 PM EEST                  * 
 * Generated by:    mlawns                                                  * 
 * Version:         SAS Data Integration Studio 4.904                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5M8HTKH.BO000255);
%let etls_jobName = %nrquote(meh_resu.ecl_obl);
%let etls_userID = %nrquote(mlawns);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */ 
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

%preprocess_std;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU00063C * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    meh_isar.ECL_OBL - meh_isar.ecl_obl   A5M8HTKH.BB000470 * 
 * Target Table:    Extract - work.W2WEG819               A5M8HTKH.BR0004I9 * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU00063C);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(meh_isar.ecl_obl); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W2WEG819;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create table work.W2WEG819 as
      select
         information_date,
         type_of_run_cd,
         application_id,
         partner_name,
         application_status,
         total_credit_amount,
         market_value,
         ecl_amt,
         stage   
            format = 8.,
         UC_pd_class_nr   
            format = 8.,
         UC_pd_class_value,
         lgd_future_1,
         ead_future_1,
         pd_actual_future_1,
         calculated_end_date,
         loaded_date as loaded_dt   
            label = '%sysfunc(round(%sysfunc(datetime()),1))'
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W2WEG819;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract **/

/*==========================================================================* 
 * Step:            history                               A5M8HTKH.BU00063D * 
 * Transform:       history                                                 * 
 * Description:     Executes history management on connected table          * 
 *                                                                          * 
 * Source Table:    Extract - work.W2WEG819               A5M8HTKH.BR0004I9 * 
 * Target Table:    meh_resu.ECL_OBL                      A5M8HTKH.BB000471 * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU00063D);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W2WEG819); 

%let _INPUT_count = 1; 
%let _INPUT = work.W2WEG819;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Extract_A5M8HTKH.BR0004I9%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.W2WEG819;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/Extract_A5M8HTKH.BR0004I9%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = meh_resu.ECL_OBL;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(&altercommand.);
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/dw_solution/meh/data/resu/meh_resu.ECL_OBL%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date application_id partner_name total_credit_amount 
        market_value ecl_amt stage UC_pd_class_nr UC_pd_class_value 
        lgd_future_1 ead_future_1 pd_actual_future_1 calculated_end_date 
        loaded_dt;

%let _OUTPUT0 = meh_resu.ECL_OBL;
%let _OUTPUT0_connect = null;
%let _OUTPUT0_engine = BASE;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote(&altercommand.);
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/dw_solution/meh/data/resu/meh_resu.ECL_OBL%(Table%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date application_id partner_name total_credit_amount 
        market_value ecl_amt stage UC_pd_class_nr UC_pd_class_value 
        lgd_future_1 ead_future_1 pd_actual_future_1 calculated_end_date 
        loaded_dt;


%let dimfields = ;
%let dimfields_count = 0;
%let dimfields0 = 0;
%let dimfields = ;

/* List of target columns to keep  */ 
%let _keep = information_date application_id partner_name total_credit_amount 
        market_value ecl_amt stage UC_pd_class_nr UC_pd_class_value 
        lgd_future_1 ead_future_1 pd_actual_future_1 calculated_end_date 
        loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date application_id partner_name total_credit_amount 
        market_value ecl_amt stage UC_pd_class_nr UC_pd_class_value 
        lgd_future_1 ead_future_1 pd_actual_future_1 calculated_end_date 
        loaded_dt;
%history(source=&_INPUT0.,target=&_OUTPUT0.,metapath=&_OUTPUT0_path.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

/*---- Create the indexes for a table  ----*/ 
%put %str(NOTE: Creating indexes ...);
proc datasets lib = meh_resu nolist; 
   modify ECL_OBL(&altercommand. ); 
      index create primary_index = (information_date application_id)
         / unique;
quit; 

%rcSet(&syserr); 



/** Step end history **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/*---- Start of Post-Process Code  ----*/ 

%postprocess_std;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

