/**************************************************************************** 
 * Job:             meh_resu.pd_actual_lifetime_bdb       A5M8HTKH.BO0000ZV * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: 217.29.235.142                                          * 
 * Port:            8563                                                    * 
 * Location:        /dw_solution/meh/programs/jobs                          * 
 *                                                                          * 
 * Server:          SASApp                                A5M8HTKH.AS000002 * 
 *                                                                          * 
 * Source Table:    meh_isar.PD_ACTUAL_LIFETIME_BDB       A5M8HTKH.BB0002NH * 
 * Target Table:    meh_resu.PD_ACTUAL_LIFETIME_BDB       A5M8HTKH.BB0002PX * 
 *                                                                          * 
 * Generated on:    Monday, April 6, 2020 1:36:22 PM EEST                   * 
 * Generated by:    mlawns                                                  * 
 * Version:         SAS Data Integration Studio 4.903                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5M8HTKH.BO0000ZV);
%let etls_jobName = %nrquote(meh_resu.pd_actual_lifetime_bdb);
%let etls_userID = %nrquote(mlawns);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */ 
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

%preprocess_std;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU0003N4 * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    meh_isar.PD_ACTUAL_LIFETIME_BDB       A5M8HTKH.BB0002NH * 
 * Target Table:    Extract - work.W87VM0VU               A5M8HTKH.BR0002IT * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0003N4);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(meh_isar.PD_ACTUAL_LIFETIME_BDB); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W87VM0VU;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W87VM0VU as
      select
         (&active_date) as information_date length = 4
            format = FINDFDD10.
            label = 'Information date of the record',
         bdb_account_id,
         type_of_run_cd,
         bb_ticker_id,
         pd_actual_lifetime_bdb,
         pd_actual_12m,
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = DATETIME20.
            label = 'Load timestamp (date & time)'
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W87VM0VU;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract **/

/*==========================================================================* 
 * Step:            history                               A5M8HTKH.BU0003N5 * 
 * Transform:       history                                                 * 
 * Description:     Executes history management on connected table          * 
 *                                                                          * 
 * Source Table:    Extract - work.W87VM0VU               A5M8HTKH.BR0002IT * 
 * Target Table:    meh_resu.PD_ACTUAL_LIFETIME_BDB       A5M8HTKH.BB0002PX * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0003N5);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W87VM0VU); 

%let _INPUT_count = 1; 
%let _INPUT = work.W87VM0VU;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = VIEW;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Extract_A5M8HTKH.BR0002IT%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.W87VM0VU;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = VIEW;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/Extract_A5M8HTKH.BR0002IT%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = meh_resu.PD_ACTUAL_LIFETIME_BDB;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT_path = %nrquote(/dw_solution/meh/data/resu/meh_resu.PD_ACTUAL_LIFETIME_BDB%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote(PD actual lifetime bond, depenture and bankaccount %(treasury%));
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bdb_account_id type_of_run_cd bb_ticker_id 
        pd_actual_lifetime_bdb pd_actual_12m loaded_dt;

%let _OUTPUT0 = meh_resu.PD_ACTUAL_LIFETIME_BDB;
%let _OUTPUT0_connect = null;
%let _OUTPUT0_engine = BASE;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_path = %nrquote(/dw_solution/meh/data/resu/meh_resu.PD_ACTUAL_LIFETIME_BDB%(Table%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote(PD actual lifetime bond, depenture and bankaccount %(treasury%));
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bdb_account_id type_of_run_cd bb_ticker_id 
        pd_actual_lifetime_bdb pd_actual_12m loaded_dt;


%let dimfields = ;
%let dimfields_count = 0;
%let dimfields0 = 0;
%let dimfields = ;

/* List of target columns to keep  */ 
%let _keep = information_date bdb_account_id type_of_run_cd bb_ticker_id 
        pd_actual_lifetime_bdb pd_actual_12m loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bdb_account_id type_of_run_cd bb_ticker_id 
        pd_actual_lifetime_bdb pd_actual_12m loaded_dt;
%history(source=&_INPUT0.,target=&_OUTPUT0.,metapath=&_OUTPUT0_path.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

/*---- Create the indexes for a table  ----*/ 
%put %str(NOTE: Creating indexes ...);
proc datasets lib = meh_resu nolist; 
   modify PD_ACTUAL_LIFETIME_BDB(&altercommand. ); 
      index create primary_index = (information_date bdb_account_id type_of_run_cd)
         / unique;
quit; 

%rcSet(&syserr); 



/** Step end history **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/*---- Start of Post-Process Code  ----*/ 

%postprocess_std;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

