/**************************************************************************** 
 * Job:             meh_resu.lgd_future_llg               A5M8HTKH.BO0000ZM * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: 217.29.235.142                                          * 
 * Port:            8563                                                    * 
 * Location:        /dw_solution/meh/programs/jobs                          * 
 *                                                                          * 
 * Server:          SASApp                                A5M8HTKH.AS000002 * 
 *                                                                          * 
 * Source Table:    meh_isar.LGD_FUTURE_LLG               A5M8HTKH.BB0002N8 * 
 * Target Table:    meh_resu.LGD_FUTURE_LLG               A5M8HTKH.BB0002OX * 
 *                                                                          * 
 * Generated on:    Monday, April 6, 2020 1:35:48 PM EEST                   * 
 * Generated by:    mlawns                                                  * 
 * Version:         SAS Data Integration Studio 4.903                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5M8HTKH.BO0000ZM);
%let etls_jobName = %nrquote(meh_resu.lgd_future_llg);
%let etls_userID = %nrquote(mlawns);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */ 
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

%preprocess_std;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU0003MM * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    meh_isar.LGD_FUTURE_LLG               A5M8HTKH.BB0002N8 * 
 * Target Table:    Extract - work.W87VM0VU               A5M8HTKH.BR0002IK * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0003MM);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(meh_isar.LGD_FUTURE_LLG); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W87VM0VU;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W87VM0VU as
      select
         (&active_date) as information_date length = 4
            format = findfdd10.
            label = 'Information date of the record',
         account_id,
         customer_id,
         bank_id   
            label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
         type_of_run_cd,
         lgd_future_1,
         lgd_future_2,
         lgd_future_3,
         lgd_future_4,
         lgd_future_5,
         lgd_future_6,
         lgd_future_7,
         lgd_future_8,
         lgd_future_9,
         lgd_future_10,
         lgd_future_11,
         lgd_future_12,
         lgd_future_13,
         lgd_future_14,
         lgd_future_15,
         lgd_future_16,
         lgd_future_17,
         lgd_future_18,
         lgd_future_19,
         lgd_future_20,
         lgd_future_21,
         lgd_future_22,
         lgd_future_23,
         lgd_future_24,
         lgd_future_25,
         lgd_future_26,
         lgd_future_27,
         lgd_future_28,
         lgd_future_29,
         lgd_future_30,
         lgd_future_31,
         lgd_future_32,
         lgd_future_33,
         lgd_future_34,
         lgd_future_35,
         lgd_future_36,
         lgd_future_37,
         lgd_future_38,
         lgd_future_39,
         lgd_future_40,
         lgd_future_41,
         lgd_future_42,
         lgd_future_43,
         lgd_future_44,
         lgd_future_45,
         lgd_future_46,
         lgd_future_47,
         lgd_future_48,
         lgd_future_49,
         lgd_future_50,
         lgd_group,
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = DATETIME20.
            label = 'Load timestamp (date & time)'
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W87VM0VU;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract **/

/*==========================================================================* 
 * Step:            history                               A5M8HTKH.BU0003MN * 
 * Transform:       history                                                 * 
 * Description:     Executes history management on connected table          * 
 *                                                                          * 
 * Source Table:    Extract - work.W87VM0VU               A5M8HTKH.BR0002IK * 
 * Target Table:    meh_resu.LGD_FUTURE_LLG               A5M8HTKH.BB0002OX * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0003MN);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W87VM0VU); 

%let _INPUT_count = 1; 
%let _INPUT = work.W87VM0VU;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = VIEW;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Extract_A5M8HTKH.BR0002IK%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.W87VM0VU;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = VIEW;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/Extract_A5M8HTKH.BR0002IK%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = meh_resu.LGD_FUTURE_LLG;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT_path = %nrquote(/dw_solution/meh/data/resu/meh_resu.LGD_FUTURE_LLG%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote(LGD future loan, limit and guarantee);
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date account_id customer_id bank_id type_of_run_cd 
        lgd_future_1 lgd_future_2 lgd_future_3 lgd_future_4 lgd_future_5 
        lgd_future_6 lgd_future_7 lgd_future_8 lgd_future_9 lgd_future_10 
        lgd_future_11 lgd_future_12 lgd_future_13 lgd_future_14 lgd_future_15 
        lgd_future_16 lgd_future_17 lgd_future_18 lgd_future_19 lgd_future_20 
        lgd_future_21 lgd_future_22 lgd_future_23 lgd_future_24 lgd_future_25 
        lgd_future_26 lgd_future_27 lgd_future_28 lgd_future_29 lgd_future_30 
        lgd_future_31 lgd_future_32 lgd_future_33 lgd_future_34 lgd_future_35 
        lgd_future_36 lgd_future_37 lgd_future_38 lgd_future_39 lgd_future_40 
        lgd_future_41 lgd_future_42 lgd_future_43 lgd_future_44 lgd_future_45 
        lgd_future_46 lgd_future_47 lgd_future_48 lgd_future_49 lgd_future_50 
        lgd_group loaded_dt;

%let _OUTPUT0 = meh_resu.LGD_FUTURE_LLG;
%let _OUTPUT0_connect = null;
%let _OUTPUT0_engine = BASE;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_path = %nrquote(/dw_solution/meh/data/resu/meh_resu.LGD_FUTURE_LLG%(Table%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote(LGD future loan, limit and guarantee);
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date account_id customer_id bank_id type_of_run_cd 
        lgd_future_1 lgd_future_2 lgd_future_3 lgd_future_4 lgd_future_5 
        lgd_future_6 lgd_future_7 lgd_future_8 lgd_future_9 lgd_future_10 
        lgd_future_11 lgd_future_12 lgd_future_13 lgd_future_14 lgd_future_15 
        lgd_future_16 lgd_future_17 lgd_future_18 lgd_future_19 lgd_future_20 
        lgd_future_21 lgd_future_22 lgd_future_23 lgd_future_24 lgd_future_25 
        lgd_future_26 lgd_future_27 lgd_future_28 lgd_future_29 lgd_future_30 
        lgd_future_31 lgd_future_32 lgd_future_33 lgd_future_34 lgd_future_35 
        lgd_future_36 lgd_future_37 lgd_future_38 lgd_future_39 lgd_future_40 
        lgd_future_41 lgd_future_42 lgd_future_43 lgd_future_44 lgd_future_45 
        lgd_future_46 lgd_future_47 lgd_future_48 lgd_future_49 lgd_future_50 
        lgd_group loaded_dt;


%let dimfields = ;
%let dimfields_count = 0;
%let dimfields0 = 0;
%let dimfields = ;

/* List of target columns to keep  */ 
%let _keep = information_date account_id customer_id bank_id type_of_run_cd 
        lgd_future_1 lgd_future_2 lgd_future_3 lgd_future_4 lgd_future_5 
        lgd_future_6 lgd_future_7 lgd_future_8 lgd_future_9 lgd_future_10 
        lgd_future_11 lgd_future_12 lgd_future_13 lgd_future_14 lgd_future_15 
        lgd_future_16 lgd_future_17 lgd_future_18 lgd_future_19 lgd_future_20 
        lgd_future_21 lgd_future_22 lgd_future_23 lgd_future_24 lgd_future_25 
        lgd_future_26 lgd_future_27 lgd_future_28 lgd_future_29 lgd_future_30 
        lgd_future_31 lgd_future_32 lgd_future_33 lgd_future_34 lgd_future_35 
        lgd_future_36 lgd_future_37 lgd_future_38 lgd_future_39 lgd_future_40 
        lgd_future_41 lgd_future_42 lgd_future_43 lgd_future_44 lgd_future_45 
        lgd_future_46 lgd_future_47 lgd_future_48 lgd_future_49 lgd_future_50 
        lgd_group loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date account_id customer_id bank_id type_of_run_cd 
        lgd_future_1 lgd_future_2 lgd_future_3 lgd_future_4 lgd_future_5 
        lgd_future_6 lgd_future_7 lgd_future_8 lgd_future_9 lgd_future_10 
        lgd_future_11 lgd_future_12 lgd_future_13 lgd_future_14 lgd_future_15 
        lgd_future_16 lgd_future_17 lgd_future_18 lgd_future_19 lgd_future_20 
        lgd_future_21 lgd_future_22 lgd_future_23 lgd_future_24 lgd_future_25 
        lgd_future_26 lgd_future_27 lgd_future_28 lgd_future_29 lgd_future_30 
        lgd_future_31 lgd_future_32 lgd_future_33 lgd_future_34 lgd_future_35 
        lgd_future_36 lgd_future_37 lgd_future_38 lgd_future_39 lgd_future_40 
        lgd_future_41 lgd_future_42 lgd_future_43 lgd_future_44 lgd_future_45 
        lgd_future_46 lgd_future_47 lgd_future_48 lgd_future_49 lgd_future_50 
        lgd_group loaded_dt;
%history(source=&_INPUT0.,target=&_OUTPUT0.,metapath=&_OUTPUT0_path.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

/*---- Create the indexes for a table  ----*/ 
%put %str(NOTE: Creating indexes ...);
proc datasets lib = meh_resu nolist; 
   modify LGD_FUTURE_LLG(&altercommand. ); 
      index create primary_index = (information_date account_id customer_id bank_id type_of_run_cd)
         / unique;
quit; 

%rcSet(&syserr); 



/** Step end history **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/*---- Start of Post-Process Code  ----*/ 

%postprocess_std;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

