/**************************************************************************** 
 * Job:             meh_resu.ecl_llg_out_csv              A5M8HTKH.BO00024U * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: 217.29.235.142                                          * 
 * Port:            8561                                                    * 
 * Location:        /dw_solution/meh/programs/jobs                          * 
 *                                                                          * 
 * Server:          SASApp                                A5M8HTKH.AS000002 * 
 *                                                                          * 
 * Source Table:    meh_isar.ECL_LLG                      A5M8HTKH.BB0002N4 * 
 * Target Table:    behaviour_PD.csv -                    A5M8HTKH.C100019J * 
 *                  /sasdw/prod/meh/external_files/outp                     * 
 *                  ut/behaviour_PD.csv                                     * 
 *                                                                          * 
 * Generated on:    Friday, June 17, 2022 11:46:37 AM EEST                  * 
 * Generated by:    mlawns                                                  * 
 * Version:         SAS Data Integration Studio 4.904                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5M8HTKH.BO00024U);
%let etls_jobName = %nrquote(meh_resu.ecl_llg_out_csv);
%let etls_userID = %nrquote(mlawns);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */ 
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU00064I * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    meh_isar.ECL_LLG                      A5M8HTKH.BB0002N4 * 
 * Target Table:    Extract - work.W36PZH9S               A5M8HTKH.BR0004J4 * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU00064I);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let etls_recCheckExist = 0; 
%let etls_recnt = 0; 
%macro etls_recordCheck; 
   %let etls_recCheckExist = %eval(%sysfunc(exist(meh_isar.ECL_LLG, DATA)) or 
         %sysfunc(exist(meh_isar.ECL_LLG, VIEW))); 
   
   %if (&etls_recCheckExist) %then
   %do;
      %local etls_syntaxcheck; 
      %let etls_syntaxcheck = %sysfunc(getoption(syntaxcheck)); 
      /* Turn off syntaxcheck option to perform following steps  */ 
      options nosyntaxcheck;
      
      proc contents data = meh_isar.ECL_LLG out = work.etls_contents(keep = nobs) noprint; 
      run; 
      
      data _null_; 
         set work.etls_contents (obs = 1); 
         call symput("etls_recnt", left(put(nobs,32.))); 
      run;
      
      proc datasets lib = work nolist nowarn memtype = (data view);
         delete etls_contents;
      quit;
      
      /* Reset syntaxcheck option to previous setting  */ 
      options &etls_syntaxcheck; 
   %end;
%mend etls_recordCheck;
%etls_recordCheck;

%let SYSLAST = %nrquote(meh_isar.ECL_LLG); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W36PZH9S;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create table work.W36PZH9S as
      select
         information_date,
         account_id,
         internal_pd_class_value
   from &SYSLAST
      where information_date = &active_date.
   ;
quit;

%let SYSLAST = work.W36PZH9S;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract **/

/*==========================================================================* 
 * Step:            File Writer                           A5M8HTKH.BU00060T * 
 * Transform:       File Writer                                             * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    Extract - work.W36PZH9S               A5M8HTKH.BR0004J4 * 
 * Target Table:    behaviour_PD.csv -                    A5M8HTKH.C100019J * 
 *                  /sasdw/prod/meh/external_files/outp                     * 
 *                  ut/behaviour_PD.csv                                     * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU00060T);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let etls_recCheckExist = 0; 
%let etls_recnt = 0; 
%macro etls_recordCheck; 
   %let etls_recCheckExist = %eval(%sysfunc(exist(work.W36PZH9S, DATA)) or 
         %sysfunc(exist(work.W36PZH9S, VIEW))); 
   
   %if (&etls_recCheckExist) %then
   %do;
      %local etls_syntaxcheck; 
      %let etls_syntaxcheck = %sysfunc(getoption(syntaxcheck)); 
      /* Turn off syntaxcheck option to perform following steps  */ 
      options nosyntaxcheck;
      
      proc contents data = work.W36PZH9S out = work.etls_contents(keep = nobs) noprint; 
      run; 
      
      data _null_; 
         set work.etls_contents (obs = 1); 
         call symput("etls_recnt", left(put(nobs,32.))); 
      run;
      
      proc datasets lib = work nolist nowarn memtype = (data view);
         delete etls_contents;
      quit;
      
      /* Reset syntaxcheck option to previous setting  */ 
      options &etls_syntaxcheck; 
   %end;
%mend etls_recordCheck;
%etls_recordCheck;

%let SYSLAST = %nrquote(work.W36PZH9S); 

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W37FQTYO;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W37FQTYO as
      select
         (TRIM(LEFT(PUT(information_date,yymmddn8.)))) as information_date length = 20
            label = 'Information date of the record',
         account_id,
         (TRIM(LEFT(PUT(internal_pd_class_value,numx15.5)))) as internal_pd_class_value length = 20,
         (cat(put(datepart(datetime()),yymmddn8.),':',put(timepart(datetime()),tod5.))) as created_dt length = 20
            label = 'Creation Date of the CSV File'
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W37FQTYO;

data _null_; 
   set &SYSLAST; 
      attrib information_date length = $20; 
      attrib account_id length = $20; 
      attrib internal_pd_class_value length = $20; 
      attrib created_dt length = $20; 
      file '/sasdw/prod/meh/external_files/output/behaviour_PD.csv' dlm=';';
      
         put 
            information_date
            account_id
            internal_pd_class_value
            created_dt
            ;

run; 

%rcSet(&syserr); 

/*---- Start of Post-Process Code  ----*/ 

/*  file transferr */
/* The output file will be transfered to the crosskey server */
/* using a secure SFT command as shown */
%macro test_env;
%if &syshostname = aablprdsas11 %then %do;
    data _null_;
    	call system ('/sasdw/prod/meh/scripts/file_trans.sh');
    run;
%end;
%else %do;
	data _null_; 
   /* test sysrtem */
    	call system ('/sasdw/test/meh/scripts/file_trans.sh');
   /*stage system */
      *call system ('scp -i ~/.ssh/sftp_key /sasdw/test/meh/external_files/output/behaviour_PD.csv ABCOMTDW1@CBANKST1:/behaviour_PD.csv');
    run;
%end;

%mend;
%test_env;

/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 



/** Step end File Writer **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

