/**************************************************************************** 
 * Job:             meh_dm.account_exp_obl                A5M8HTKH.BO00024W * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: 217.29.235.142                                          * 
 * Port:            8561                                                    * 
 * Location:        /dw_solution/meh/programs/jobs                          * 
 *                                                                          * 
 * Server:          SASApp                                A5M8HTKH.AS000002 * 
 *                                                                          * 
 * Source Tables:   dwh_dw.LOAN_APPLICATION               A5M8HTKH.BB00035Y * 
 *                  dwh_dw.LOAN_APPLICATION_CAL           A5M8HTKH.BB00036S * 
 *                  dwh_dw.LOAN_APPLICATION_COLL_EX_REP   A5M8HTKH.BB000369 * 
 * Target Table:    meh_dm.ACCOUNT_EXP_OBL                A5M8HTKH.BB000475 * 
 *                                                                          * 
 * Generated on:    den 5 juli 2023 kl 12:09 EEST                           * 
 * Generated by:    odannstr                                                * 
 * Version:         SAS Data Integration Studio 4.905                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5M8HTKH.BO00024W);
%let etls_jobName = %nrquote(meh_dm.account_exp_obl);
%let etls_userID = %nrquote(odannstr);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */ 
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*==========================================================================* 
 * Step:            Join                                  A5M8HTKH.BU000614 * 
 * Transform:       Join                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Tables:   dwh_dw.LOAN_APPLICATION               A5M8HTKH.BB00035Y * 
 *                  dwh_dw.LOAN_APPLICATION_CAL           A5M8HTKH.BB00036S * 
 *                  dwh_dw.LOAN_APPLICATION_COLL_EX_REP   A5M8HTKH.BB000369 * 
 * Target Table:    Join - work.W1OY7XNR                  A5M8HTKH.BR0004I3 * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU000614);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let etls_recCheckExist = 0; 
%let etls_recnt = 0; 
%macro etls_recordCheck; 
   %let etls_recCheckExist = %eval(%sysfunc(exist(dwh_dw.LOAN_APPLICATION, DATA)) or 
         %sysfunc(exist(dwh_dw.LOAN_APPLICATION, VIEW))); 
   
   %if (&etls_recCheckExist) %then
   %do;
      %local etls_syntaxcheck; 
      %let etls_syntaxcheck = %sysfunc(getoption(syntaxcheck)); 
      /* Turn off syntaxcheck option to perform following steps  */ 
      options nosyntaxcheck;
      
      proc contents data = dwh_dw.LOAN_APPLICATION (&altercommand.)
       out = work.etls_contents(keep = nobs) noprint; 
      run; 
      
      data _null_; 
         set work.etls_contents (obs = 1); 
         call symput("etls_recnt", left(put(nobs,32.))); 
      run;
      
      proc datasets lib = work nolist nowarn memtype = (data view);
         delete etls_contents;
      quit;
      
      /* Reset syntaxcheck option to previous setting  */ 
      options &etls_syntaxcheck; 
   %end;
%mend etls_recordCheck;
%etls_recordCheck;

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete W1OY7XNR;
quit;

proc sql;
   create view work.W1OY7XNR as
   select
      LOAN_APPLICATION.information_date length = 8   
         format = FINDFDD10.
         label = 'Information date',
      LOAN_APPLICATION.application_id length = 50   
         label = 'The application ID',
      LOAN_APPLICATION.partner_name length = 50   
         label = 'The partner’s name',
      case  
      when LOAN_APPLICATION.application_purpose = 'INCREASE' then LOAN_APPLICATION.desired_increase_amount  
      else LOAN_APPLICATION.total_credit_amount  
      end as total_credit_amount length = 8   
         format = 18.1
         label = 'Total applied credit amount',
      LOAN_APPLICATION.application_status length = 50   
         label = 'The status of application',
      LOAN_APPLICATION.application_pd length = 8   
         format = 18.5
         label = 'Applications probability of default',
      LOAN_APPLICATION_CAL.ltv_system_ratio length = 8   
         format = 18.2,
      LOAN_APPLICATION_CAL.lti_system_ratio length = 8   
         format = 18.2,
      LOAN_APPLICATION_CAL.ltv_application_ratio length = 8   
         format = 18.2,
      LOAN_APPLICATION_CAL.lti_application_ratio length = 8   
         format = 18.2,
      LOAN_APPLICATION_COLL_EX_REP.market_value length = 8   
         format = 18.,
      LOAN_APPLICATION.application_type length = 50   
         label = 'Type of application'
   from
      dwh_dw.LOAN_APPLICATION
      (
         &altercommand.
      ) as LOAN_APPLICATION left join 
      dwh_dw.LOAN_APPLICATION_CAL
      (
         &altercommand.
      ) as LOAN_APPLICATION_CAL
         on
         (
            LOAN_APPLICATION.information_date = LOAN_APPLICATION_CAL.information_date
            and LOAN_APPLICATION.application_id = LOAN_APPLICATION_CAL.application_id
         ) left join 
      dwh_dw.LOAN_APPLICATION_COLL_EX_REP
      (
         &altercommand.
      ) as LOAN_APPLICATION_COLL_EX_REP
         on
         (
            LOAN_APPLICATION.information_date = LOAN_APPLICATION_COLL_EX_REP.information_date
            and LOAN_APPLICATION.application_id = LOAN_APPLICATION_COLL_EX_REP.application_id
         )
   where
      LOAN_APPLICATION.information_date = &active_date.
      and (LOAN_APPLICATION.application_status IN ('AGREEMENT_SENT', 'AGREEMENT_SIGNED' , 'WAITING AGREEMENT_SIGNED')
      or (LOAN_APPLICATION.application_status = 'PRELIMINARY_APPROVED_CREDIT_DECISION'
      and LOAN_APPLICATION.application_purpose = 'PROMISE'))
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Join **/

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU000636 * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    Join - work.W1OY7XNR                  A5M8HTKH.BR0004I3 * 
 * Target Table:    Extract - work.W1OXNKKL               A5M8HTKH.BR0004I4 * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU000636);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let etls_recnt = -1;
%let SYSLAST = %nrquote(work.W1OY7XNR); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W1OXNKKL;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W1OXNKKL as
      select
         information_date,
         application_id,
         partner_name,
         total_credit_amount,
         application_status,
         application_pd,
         ltv_system_ratio,
         lti_system_ratio,
         ltv_application_ratio,
         lti_application_ratio,
         market_value,
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = datetime20.
            label = 'Load timestamp (date & time)',
         application_type
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W1OXNKKL;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract **/

/*==========================================================================* 
 * Step:            history                               A5M8HTKH.BU000637 * 
 * Transform:       history                                                 * 
 * Description:     Executes history management on connected table          * 
 *                                                                          * 
 * Source Table:    Extract - work.W1OXNKKL               A5M8HTKH.BR0004I4 * 
 * Target Table:    meh_dm.ACCOUNT_EXP_OBL                A5M8HTKH.BB000475 * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU000637);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let etls_recnt = -1;
%let SYSLAST = %nrquote(work.W1OXNKKL); 

%let _INPUT_count = 1; 
%let _INPUT = work.W1OXNKKL;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = VIEW;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Extract_A5M8HTKH.BR0004I4%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.W1OXNKKL;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = VIEW;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/Extract_A5M8HTKH.BR0004I4%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = meh_dm.ACCOUNT_EXP_OBL;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(&altercommand.);
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/dw_solution/meh/data/dm/meh_dm.ACCOUNT_EXP_OBL%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date application_id partner_name total_credit_amount 
        application_status application_pd ltv_system_ratio lti_system_ratio 
        ltv_application_ratio lti_application_ratio market_value 
        application_type loaded_dt;

%let _OUTPUT0 = meh_dm.ACCOUNT_EXP_OBL;
%let _OUTPUT0_connect = null;
%let _OUTPUT0_engine = BASE;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote(&altercommand.);
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/dw_solution/meh/data/dm/meh_dm.ACCOUNT_EXP_OBL%(Table%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date application_id partner_name total_credit_amount 
        application_status application_pd ltv_system_ratio lti_system_ratio 
        ltv_application_ratio lti_application_ratio market_value 
        application_type loaded_dt;


%let dimfields = ;
%let dimfields_count = 0;
%let dimfields0 = 0;
%let dimfields = ;

/* List of target columns to keep  */ 
%let _keep = information_date application_id partner_name total_credit_amount 
        application_status application_pd ltv_system_ratio lti_system_ratio 
        ltv_application_ratio lti_application_ratio market_value 
        application_type loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date application_id partner_name total_credit_amount 
        application_status application_pd ltv_system_ratio lti_system_ratio 
        ltv_application_ratio lti_application_ratio market_value 
        application_type loaded_dt;
%history(source=&_INPUT0.,target=&_OUTPUT0.,metapath=&_OUTPUT0_path.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

/*---- Create the indexes for a table  ----*/ 
%put %str(NOTE: Creating indexes ...);
proc datasets lib = meh_dm nolist; 
   modify ACCOUNT_EXP_OBL(&altercommand. ); 
      index create primary_index = (information_date application_id)
         / unique;
quit; 

%rcSet(&syserr); 



/** Step end history **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

