/**************************************************************************** 
 * Job:             mel_resu.ead_future_cc                A5ZNM6KG.BO0003L3 * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: olandsbanken-metadata                                   * 
 * Port:            8563                                                    * 
 * Location:        /dw_solution/mel/programs/jobs                          * 
 *                                                                          * 
 * Server:          DEV_App                               A5ZNM6KG.AS000005 * 
 *                                                                          * 
 * Source Table:    mel_isar.EAD_FUTURE_CC                A5ZNM6KG.BG0004LR * 
 * Target Table:    mel_resu.EAD_FUTURE_CC                A5ZNM6KG.BG0004PO * 
 *                                                                          * 
 * Generated on:    Thursday, March 21, 2019 3:33:33 PM EET                 * 
 * Generated by:    jko                                                     * 
 * Version:         SAS Data Integration Studio 4.901                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5ZNM6KG.BO0003L3);
%let etls_jobName = %nrquote(mel_resu.ead_future_cc);
%let etls_userID = %nrquote(jko);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

%preprocess_std;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            Extract                               A5ZNM6KG.BS0003EQ * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    mel_isar.EAD_FUTURE_CC                A5ZNM6KG.BG0004LR * 
 * Target Table:    Extract - work.W87VM0VU               A5ZNM6KG.BV0002T0 * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0003EQ);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mel_isar.EAD_FUTURE_CC); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W87VM0VU;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W87VM0VU as
      select
         (&active_date) as information_date length = 4
            format = FINDFDD10.
            informat = DDMMYY10.
            label = 'Information date of the record',
         cc_account_id,
         type_of_run_cd,
         source_company_id,
         ead_future_1,
         ead_future_2,
         ead_future_3,
         ead_future_4,
         ead_future_5,
         ead_future_6,
         ead_future_7,
         ead_future_8,
         ead_future_9,
         ead_future_10,
         ead_future_11,
         ead_future_12,
         ead_future_13,
         ead_future_14,
         ead_future_15,
         ead_future_16,
         ead_future_17,
         ead_future_18,
         ead_future_19,
         ead_future_20,
         ead_future_21,
         ead_future_22,
         ead_future_23,
         ead_future_24,
         ead_future_25,
         ead_future_26,
         ead_future_27,
         ead_future_28,
         ead_future_29,
         ead_future_30,
         ead_future_31,
         ead_future_32,
         ead_future_33,
         ead_future_34,
         ead_future_35,
         ead_future_36,
         ead_future_37,
         ead_future_38,
         ead_future_39,
         ead_future_40,
         ead_future_41,
         ead_future_42,
         ead_future_43,
         ead_future_44,
         ead_future_45,
         ead_future_46,
         ead_future_47,
         ead_future_48,
         ead_future_49,
         ead_future_50,
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = DATETIME20.
            label = 'Load timestamp (date & time)'
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W87VM0VU;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Extract **/

/*==========================================================================* 
 * Step:            history                               A5ZNM6KG.BS0003ER * 
 * Transform:       history                                                 * 
 * Description:     Executes history management on connected table          * 
 *                                                                          * 
 * Source Table:    Extract - work.W87VM0VU               A5ZNM6KG.BV0002T0 * 
 * Target Table:    mel_resu.EAD_FUTURE_CC                A5ZNM6KG.BG0004PO * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0003ER);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W87VM0VU); 

%let _INPUT_count = 1; 
%let _INPUT = work.W87VM0VU;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = VIEW;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Extract_A5ZNM6KG.BV0002T0%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.W87VM0VU;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = VIEW;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/Extract_A5ZNM6KG.BV0002T0%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = mel_resu.EAD_FUTURE_CC;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT_path = %nrquote(/dw_solution/mel/data/resu/mel_resu.EAD_FUTURE_CC%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote(EAD future credit card);
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date cc_account_id type_of_run_cd source_company_id 
        ead_future_1 ead_future_2 ead_future_3 ead_future_4 ead_future_5 
        ead_future_6 ead_future_7 ead_future_8 ead_future_9 ead_future_10 
        ead_future_11 ead_future_12 ead_future_13 ead_future_14 ead_future_15 
        ead_future_16 ead_future_17 ead_future_18 ead_future_19 ead_future_20 
        ead_future_21 ead_future_22 ead_future_23 ead_future_24 ead_future_25 
        ead_future_26 ead_future_27 ead_future_28 ead_future_29 ead_future_30 
        ead_future_31 ead_future_32 ead_future_33 ead_future_34 ead_future_35 
        ead_future_36 ead_future_37 ead_future_38 ead_future_39 ead_future_40 
        ead_future_41 ead_future_42 ead_future_43 ead_future_44 ead_future_45 
        ead_future_46 ead_future_47 ead_future_48 ead_future_49 ead_future_50 
        loaded_dt;

%let _OUTPUT0 = mel_resu.EAD_FUTURE_CC;
%let _OUTPUT0_connect = null;
%let _OUTPUT0_engine = BASE;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_path = %nrquote(/dw_solution/mel/data/resu/mel_resu.EAD_FUTURE_CC%(Table%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote(EAD future credit card);
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date cc_account_id type_of_run_cd source_company_id 
        ead_future_1 ead_future_2 ead_future_3 ead_future_4 ead_future_5 
        ead_future_6 ead_future_7 ead_future_8 ead_future_9 ead_future_10 
        ead_future_11 ead_future_12 ead_future_13 ead_future_14 ead_future_15 
        ead_future_16 ead_future_17 ead_future_18 ead_future_19 ead_future_20 
        ead_future_21 ead_future_22 ead_future_23 ead_future_24 ead_future_25 
        ead_future_26 ead_future_27 ead_future_28 ead_future_29 ead_future_30 
        ead_future_31 ead_future_32 ead_future_33 ead_future_34 ead_future_35 
        ead_future_36 ead_future_37 ead_future_38 ead_future_39 ead_future_40 
        ead_future_41 ead_future_42 ead_future_43 ead_future_44 ead_future_45 
        ead_future_46 ead_future_47 ead_future_48 ead_future_49 ead_future_50 
        loaded_dt;


%let dimfields = ;
%let dimfields_count = 0;
%let dimfields0 = 0;
%let dimfields = ;

/* List of target columns to keep  */ 
%let _keep = information_date cc_account_id type_of_run_cd source_company_id 
        ead_future_1 ead_future_2 ead_future_3 ead_future_4 ead_future_5 
        ead_future_6 ead_future_7 ead_future_8 ead_future_9 ead_future_10 
        ead_future_11 ead_future_12 ead_future_13 ead_future_14 ead_future_15 
        ead_future_16 ead_future_17 ead_future_18 ead_future_19 ead_future_20 
        ead_future_21 ead_future_22 ead_future_23 ead_future_24 ead_future_25 
        ead_future_26 ead_future_27 ead_future_28 ead_future_29 ead_future_30 
        ead_future_31 ead_future_32 ead_future_33 ead_future_34 ead_future_35 
        ead_future_36 ead_future_37 ead_future_38 ead_future_39 ead_future_40 
        ead_future_41 ead_future_42 ead_future_43 ead_future_44 ead_future_45 
        ead_future_46 ead_future_47 ead_future_48 ead_future_49 ead_future_50 
        loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date cc_account_id type_of_run_cd source_company_id 
        ead_future_1 ead_future_2 ead_future_3 ead_future_4 ead_future_5 
        ead_future_6 ead_future_7 ead_future_8 ead_future_9 ead_future_10 
        ead_future_11 ead_future_12 ead_future_13 ead_future_14 ead_future_15 
        ead_future_16 ead_future_17 ead_future_18 ead_future_19 ead_future_20 
        ead_future_21 ead_future_22 ead_future_23 ead_future_24 ead_future_25 
        ead_future_26 ead_future_27 ead_future_28 ead_future_29 ead_future_30 
        ead_future_31 ead_future_32 ead_future_33 ead_future_34 ead_future_35 
        ead_future_36 ead_future_37 ead_future_38 ead_future_39 ead_future_40 
        ead_future_41 ead_future_42 ead_future_43 ead_future_44 ead_future_45 
        ead_future_46 ead_future_47 ead_future_48 ead_future_49 ead_future_50 
        loaded_dt;
%history(source=&_INPUT0.,target=&_OUTPUT0.,metapath=&_OUTPUT0_path.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

/*---- Create the indexes for a table  ----*/ 
%put %str(NOTE: Creating indexes ...);
proc datasets lib = mel_resu nolist; 
   modify EAD_FUTURE_CC(ALTER=&alterpass ); 
      index create primary_index = (information_date cc_account_id type_of_run_cd)
         / unique;
quit; 

%rcSet(&syserr); 



/**  Step end history **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/*---- Start of Post-Process Code  ----*/ 

%postprocess_std;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

