/**************************************************************************** 
 * Job:             mel_isar.pd_actual_lifetime_bdb       A5ZNM6KG.BO0003PM * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: olandsbanken-metadata                                   * 
 * Port:            8563                                                    * 
 * Location:        /dw_solution/mel/programs/jobs                          * 
 *                                                                          * 
 * Server:          DEV_App                               A5ZNM6KG.AS000005 * 
 *                                                                          * 
 * Source Table:    pd_actual_lifetime_bdb.csv -          A5ZNM6KG.C10002HF * 
 *                  /sasdw/prod/mel/internal_files/outp                     * 
 *                  ut/pd_actual_lifetime_bdb.csv                           * 
 * Target Table:    mel_isar.PD_ACTUAL_LIFETIME_BDB       A5ZNM6KG.BG0004M7 * 
 *                                                                          * 
 * Generated on:    Wednesday, January 30, 2019 9:28:20 AM EET              * 
 * Generated by:    ier                                                     * 
 * Version:         SAS Data Integration Studio 4.901                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5ZNM6KG.BO0003PM);
%let etls_jobName = %nrquote(mel_isar.pd_actual_lifetime_bdb);
%let etls_userID = %nrquote(ier);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

%preprocess_std;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            File Reader                           A5ZNM6KG.BS000452 * 
 * Transform:       File Reader                                             * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    pd_actual_lifetime_bdb.csv -          A5ZNM6KG.C10002HF * 
 *                  /sasdw/prod/mel/internal_files/outp                     * 
 *                  ut/pd_actual_lifetime_bdb.csv                           * 
 * Target Table:    File Reader - work.W861EKE5           A5ZNM6KG.BV0003D5 * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS000452);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

proc datasets lib = work nolist nowarn memtype = (data view);
   delete W861EKE5;
quit;

data work.W861EKE5 / view = work.W861EKE5 ; 
   infile '/sasdw/prod/mel/internal_files/output/pd_actual_lifetime_bdb.csv'
          lrecl = 5000
          delimiter = '|'
          dsd
          missover
          firstobs = 2; 
   ; 
   attrib information_date length = $10; 
   attrib bdb_account_id length = $20; 
   attrib type_of_run_cd length = $6; 
   attrib bb_ticker_id length = $25; 
   attrib pd_actual_lifetime_bdb length = $20; 
   attrib pd_actual_12m length = $20; 
   
   input information_date bdb_account_id type_of_run_cd bb_ticker_id 
         pd_actual_lifetime_bdb pd_actual_12m; 
   
run; 

%rcSet(&syserr); 



/**  Step end File Reader **/

/*==========================================================================* 
 * Step:            Extract                               A5ZNM6KG.BS000453 * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    File Reader - work.W861EKE5           A5ZNM6KG.BV0003D5 * 
 * Target Table:    Extract - work.W87VM0VU               A5ZNM6KG.BV0003D6 * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS000453);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W861EKE5); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W87VM0VU;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W87VM0VU as
      select
         (INPUT(information_date,yymmdd10.)) as information_date length = 4
            format = findfdd10.
            label = 'Information date of the record',
         bdb_account_id,
         type_of_run_cd,
         bb_ticker_id,
         (INPUT(pd_actual_lifetime_bdb,BEST32.)) as pd_actual_lifetime_bdb length = 8
            format = 15.5
            label = 'Lifetime PD för återstående tid beräknat med aktuell data',
         (INPUT(pd_actual_12m,BEST32.)) as pd_actual_12m length = 8
            format = 15.5
            label = 'Point in time 12-månaders PD-värde (sannolikheten för fallissemang inom det kommande året)',
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = datetime20.
            label = 'Load timestamp (date & time)'
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W87VM0VU;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Extract **/

/*==========================================================================* 
 * Step:            Table Loader                          A5ZNM6KG.BS00047X * 
 * Transform:       Table Loader (Version 2.1)                              * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    Extract - work.W87VM0VU               A5ZNM6KG.BV0003D6 * 
 * Target Table:    mel_isar.PD_ACTUAL_LIFETIME_BDB       A5ZNM6KG.BG0004M7 * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS00047X);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W87VM0VU); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

%global etls_tableExist;
%global etls_numIndex;
%global etls_lastTable;
%let etls_tableExist = -1; 
%let etls_numIndex = -1; 
%let etls_lastTable = &SYSLAST; 

/*---- Define load data macro  ----*/ 

/* --------------------------------------------------------------
   Load Technique Selection: Replace - EntireTable
   Constraint and index action selections: 'ASIS','ASIS','ASIS','ASIS'
   Additional options selections... 
      Set unmapped to missing on updates: false 
   -------------------------------------------------------------- */
%macro etls_loader;

   %let etls_tableOptions = ;
   
   /* Determine if the target table exists  */ 
   %let etls_tableExist = %eval(%sysfunc(exist(mel_isar.PD_ACTUAL_LIFETIME_BDB, DATA)) or 
         %sysfunc(exist(mel_isar.PD_ACTUAL_LIFETIME_BDB, VIEW))); 
   
   %if &etls_tableExist %then 
   %do;/* table exists  */ 
      %let etls_hasPreExistingConstraint=0; 
      
      proc datasets lib = work nolist nowarn memtype = (data view);
         delete etls_commands etls_commands_F;
      quit;
      
      %let etls_otherTablesReferToThisTable=0;
      
      %macro etls_CIContents(table=,workTableOut=,inDSOptions=);
         %put NOTE: Building table listing Constraints and Indexes for: &table;
         proc datasets lib=work nolist; delete &workTableOut; quit;
         proc contents data=&table&inDSOptions out2=&workTableOut noprint; run;
         
         data &workTableOut;
            length name $60 type $20 icown idxUnique idxNoMiss $3 recreate $600;
            name = '';
            type = '';
            icown = '';
            idxUnique = '';
            idxNoMiss = '';
            recreate = '';
            set &workTableOut;
            ref = '';
            type=upcase(type);
            if type eq 'REFERENTIAL' then
            do;
               put "WARNING%QUOTE(:) Target table is referenced by constraints in"
                    " another table: " ref;
               call symput('etls_otherTablesReferToThisTable','1');
               delete;
            end;
            if type='INDEX' and ICOwn eq 'YES' then delete;
         run;
         %rcSet(&syserr); 
         
      %mend etls_CIContents;
      
      %etls_CIContents(table=mel_isar.PD_ACTUAL_LIFETIME_BDB, workTableOut=etls_commands, inDSOptions=);
      
      %if &etls_otherTablesReferToThisTable %then 
         %put WARNING%QUOTE(:) Replacing entire table will fail. Consider an alternate load technique or revising constraints.; 
      %else 
      %do; /* okay - remove foreign keys  */ 
      
         data etls_commands_F; 
            set etls_commands; 
            if upcase(type)="FOREIGN KEY" then 
            do; 
               command='ic delete '||trim(name)||';';
               output etls_commands_F; 
            end; 
         run; 
         
         %put %str(NOTE: Removing foreign keys before dropping table...);
         data _null_;
            set etls_commands_F end=eof;
            if _n_=1 then 
               call execute('proc datasets nolist lib=mel_isar;modify PD_ACTUAL_LIFETIME_BDB;');
            call execute(command);
            if eof then call execute('; quit;');
         run;
         %rcSet(&syserr); 
         
   %end; /* okay - remove foreign keys  */ 
   
   proc datasets lib = work nolist nowarn memtype = (data view);
      delete etls_commands etls_commands_F;
   quit;
   
   /*---- Drop a table  ----*/ 
   %put %str(NOTE: Dropping table ...);
   proc datasets lib = mel_isar nolist nowarn memtype = (data view);
      delete PD_ACTUAL_LIFETIME_BDB;
   quit;
   
   %rcSet(&syserr); 
   
   %let etls_tableExist = 0;
   
%end; /* table exists  */ 

/*---- Create a new table  ----*/ 
%if (&etls_tableExist eq 0) %then 
%do;  /* if table does not exist  */ 

   %put %str(NOTE: Creating table ...);
   
   data mel_isar.PD_ACTUAL_LIFETIME_BDB
           (label = 'PD actual lifetime bond, depenture and bankaccount (treasury)');
      attrib information_date length = 4
         format = FINDFDD10.
         label = 'Information date of the record'; 
      attrib bdb_account_id length = $20
         label = 'Account Number'; 
      attrib type_of_run_cd length = $6
         label = 'Type of run code'; 
      attrib bb_ticker_id length = $25
         label = 'The ticker for the counterpartry according to Bloomberg'; 
      attrib pd_actual_lifetime_bdb length = 8
         format = 15.5
         label = 'Lifetime PD för återstående tid beräknat med aktuell data'; 
      attrib pd_actual_12m length = 8
         format = 15.5
         label = 'Point in time 12-månaders PD-värde (sannolikheten för fallissemang inom det kommande året)'; 
      attrib loaded_dt length = 8
         format = DATETIME20.
         label = 'Load timestamp (date & time)'; 
      call missing(of _all_);
      stop;
   run;
   
   %rcSet(&syserr); 
   
%end;  /* if table does not exist  */ 

/*---- Append  ----*/ 
%put %str(NOTE: Appending data ...);

proc append base = mel_isar.PD_ACTUAL_LIFETIME_BDB 
   data = &etls_lastTable (&etls_tableOptions)  force ; 
 run; 

%rcSet(&syserr); 

%mend etls_loader;
%etls_loader;



/**  Step end Table Loader **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/*---- Start of Post-Process Code  ----*/ 

%postprocess_std;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

