/**************************************************************************** 
 * Job:             mel_dm.transaction_collection_cc      A5ZNM6KG.BO0003OW * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: olandsbanken-metadata                                   * 
 * Port:            8563                                                    * 
 * Location:        /dw_solution/mel/programs/jobs                          * 
 *                                                                          * 
 * Server:          DEV_App                               A5ZNM6KG.AS000005 * 
 *                                                                          * 
 * Source Table:    dw_dw.CC_INKASSO_TRANSACTION          A5ZNM6KG.BG00044U * 
 * Target Table:    mel_dm.TRANSACTION_COLLECTION_CC      A5ZNM6KG.BG0004EJ * 
 *                                                                          * 
 * Generated on:    Thursday, January 3, 2019 2:00:13 PM EET                * 
 * Generated by:    ier                                                     * 
 * Version:         SAS Data Integration Studio 4.901                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5ZNM6KG.BO0003OW);
%let etls_jobName = %nrquote(mel_dm.transaction_collection_cc);
%let etls_userID = %nrquote(ier);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

%preprocess_std;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            Extract                               A5ZNM6KG.BS0003ZM * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    dw_dw.CC_INKASSO_TRANSACTION          A5ZNM6KG.BG00044U * 
 * Target Table:    Extract - work.W5MGDWMT               A5ZNM6KG.BV00038F * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0003ZM);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.CC_INKASSO_TRANSACTION); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W5MGDWMT;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W5MGDWMT as
      select
         information_date,
         transaction_id,
         cc_account_id,
         transaction_date,
         posting_date,
         transaction_type_cd,
         credit_flag,
         account_currency_amt,
         source_company_id,
         source_system_cd,
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = DATETIME20.
            label = 'Load timestamp (date & time)'
   from &SYSLAST
      (ALTER=&alterpass)
   ;
quit;

%let SYSLAST = work.W5MGDWMT;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Extract **/

/*==========================================================================* 
 * Step:            history                               A5ZNM6KG.BS0003ZL * 
 * Transform:       history                                                 * 
 * Description:     Executes history management on connected table          * 
 *                                                                          * 
 * Source Table:    Extract - work.W5MGDWMT               A5ZNM6KG.BV00038F * 
 * Target Table:    mel_dm.TRANSACTION_COLLECTION_CC      A5ZNM6KG.BG0004EJ * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0003ZL);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W5MGDWMT); 

%let _INPUT_count = 1; 
%let _INPUT = work.W5MGDWMT;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = VIEW;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Extract_A5ZNM6KG.BV00038F%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.W5MGDWMT;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = VIEW;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/Extract_A5ZNM6KG.BV00038F%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = mel_dm.TRANSACTION_COLLECTION_CC;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT_path = %nrquote(/dw_solution/mel/data/dm/mel_dm.TRANSACTION_COLLECTION_CC%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote(Transaction collection CC table);
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date transaction_id cc_account_id transaction_date 
        posting_date transaction_type_cd credit_flag account_currency_amt 
        source_company_id source_system_cd loaded_dt;

%let _OUTPUT0 = mel_dm.TRANSACTION_COLLECTION_CC;
%let _OUTPUT0_connect = null;
%let _OUTPUT0_engine = BASE;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_path = %nrquote(/dw_solution/mel/data/dm/mel_dm.TRANSACTION_COLLECTION_CC%(Table%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote(Transaction collection CC table);
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date transaction_id cc_account_id transaction_date 
        posting_date transaction_type_cd credit_flag account_currency_amt 
        source_company_id source_system_cd loaded_dt;


%let dimfields = ;
%let dimfields_count = 0;
%let dimfields0 = 0;
%let dimfields = ;

/* List of target columns to keep  */ 
%let _keep = information_date transaction_id cc_account_id transaction_date 
        posting_date transaction_type_cd credit_flag account_currency_amt 
        source_company_id source_system_cd loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date transaction_id cc_account_id transaction_date 
        posting_date transaction_type_cd credit_flag account_currency_amt 
        source_company_id source_system_cd loaded_dt;
%history(source=&_INPUT0.,target=&_OUTPUT0.,metapath=&_OUTPUT0_path.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

/*---- Create the indexes for a table  ----*/ 
%put %str(NOTE: Creating indexes ...);
proc datasets lib = mel_dm nolist; 
   modify TRANSACTION_COLLECTION_CC(ALTER=&alterpass ); 
      index create primary_index = (information_date transaction_id cc_account_id)
         / unique;
quit; 

%rcSet(&syserr); 



/**  Step end history **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/*---- Start of Post-Process Code  ----*/ 

%postprocess_std;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

