/**************************************************************************** 
 * Job:             mel_resu.ecl_llg                      A5ZNM6KG.BO0003M1 * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: olandsbanken-metadata                                   * 
 * Port:            8563                                                    * 
 * Location:        /dw_solution/mel/programs/jobs                          * 
 *                                                                          * 
 * Server:          DEV_App                               A5ZNM6KG.AS000005 * 
 *                                                                          * 
 * Source Table:    mel_isar.ECL_LLG                      A5ZNM6KG.BG0006II * 
 * Target Table:    mel_resu.ECL_LLG                      A5ZNM6KG.BG0006IJ * 
 *                                                                          * 
 * Generated on:    Wednesday, January 30, 2019 9:46:59 AM EET              * 
 * Generated by:    makkojon                                                * 
 * Version:         SAS Data Integration Studio 4.901                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5ZNM6KG.BO0003M1);
%let etls_jobName = %nrquote(mel_resu.ecl_llg);
%let etls_userID = %nrquote(makkojon);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

%preprocess_std;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            Extract                               A5ZNM6KG.BS0003HQ * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    mel_isar.ECL_LLG                      A5ZNM6KG.BG0006II * 
 * Target Table:    Extract - work.W87VM0VU               A5ZNM6KG.BV0002UV * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0003HQ);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mel_isar.ECL_LLG); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W87VM0VU;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W87VM0VU as
      select
         (&active_date) as information_date length = 4
            format = findfdd10.
            label = 'Information date of the record',
         account_id,
         account_number_official,
         bank_id,
         type_of_run_cd,
         owner1_ssn_id,
         owner1_name,
         result_office_id,
         portfolio_cd,
         account_type_cd,
         booked_balance_amt,
         currency_cd,
         ecl_amt,
         ecl_euro_amt,
         ecl_sek_min_lvl_amt   
            label = 'ECL-value in krona minimum level monetary amount',
         ecl_euro_min_lvl_amt   
            label = 'ECL-value in euro minimum level monetary amount',
         ecl_euro_min_lvl_on_balance_amt   
            label = 'ECL-value in euro minumum level on balance monetary amount',
         ecl_euro_min_lvl_off_balance_amt   
            label = 'ECL-value in euro minumum level off balance monetary amount',
         ecl_sek_min_lvl_on_balance_amt   
            label = 'ECL-value in krona minumum level on balance monetary amount',
         ecl_sek_min_lvl_off_balance_amt   
            label = 'ECL-value in krona minumum level off balance monetary amount',
         ead_future_1,
         ead_future_1_sek   
            label = 'EAD beräknat med EAD-modell för år 1 in kronor',
         ead_future_1_euro   
            label = 'EAD beräknat med EAD-modell för år 1 in euro',
         lgd_future_1,
         pd_actual_12m,
         pd_initial_12m,
         pd_actual_lifetime,
         pd_initial_lifetime,
         pd_actual_future_1,
         stage,
         stage_previous,
         waiting_period,
         waiting_period_previous,
         proposed_stage,
         default_flg,
         forbearance_status_cd,
         overdraft_days_cnt,
         unmanaged_days_cnt,
         low_credit_risk_flg   
            label = 'Low credit risk flag',
         calculated_end_date   
            label = 'Calculated ending date',
         lgd_group,
         ecl_override_flg   
            label = 'ECL-value override flag',
         initial_date   
            label = 'Initial date of the record',
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = datetime20.
            label = 'Loaded date'
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W87VM0VU;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Extract **/

/*==========================================================================* 
 * Step:            history                               A5ZNM6KG.BS0003HR * 
 * Transform:       history                                                 * 
 * Description:     Executes history management on connected table          * 
 *                                                                          * 
 * Source Table:    Extract - work.W87VM0VU               A5ZNM6KG.BV0002UV * 
 * Target Table:    mel_resu.ECL_LLG                      A5ZNM6KG.BG0006IJ * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0003HR);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W87VM0VU); 

%let _INPUT_count = 1; 
%let _INPUT = work.W87VM0VU;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = VIEW;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Extract_A5ZNM6KG.BV0002UV%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.W87VM0VU;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = VIEW;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/Extract_A5ZNM6KG.BV0002UV%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = mel_resu.ECL_LLG;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(ALTER=&alterpass.);
%let _OUTPUT_alter = %nrquote(ALTER=&alterpass.);
%let _OUTPUT_path = %nrquote(/dw_solution/mel/data/resu/mel_resu.ECL_LLG%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote(ECL loan, limit and guarantee);
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date account_id account_number_official bank_id 
        type_of_run_cd owner1_ssn_id owner1_name result_office_id portfolio_cd 
        account_type_cd booked_balance_amt currency_cd ecl_amt ecl_euro_amt 
        ecl_sek_min_lvl_amt ecl_euro_min_lvl_amt 
        ecl_euro_min_lvl_on_balance_amt ecl_euro_min_lvl_off_balance_amt 
        ecl_sek_min_lvl_on_balance_amt ecl_sek_min_lvl_off_balance_amt 
        ead_future_1 ead_future_1_sek ead_future_1_euro lgd_future_1 
        pd_actual_12m pd_initial_12m pd_actual_lifetime pd_initial_lifetime 
        pd_actual_future_1 stage stage_previous waiting_period 
        waiting_period_previous proposed_stage default_flg 
        forbearance_status_cd overdraft_days_cnt unmanaged_days_cnt 
        low_credit_risk_flg calculated_end_date lgd_group ecl_override_flg 
        initial_date loaded_dt;

%let _OUTPUT0 = mel_resu.ECL_LLG;
%let _OUTPUT0_connect = null;
%let _OUTPUT0_engine = BASE;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote(ALTER=&alterpass.);
%let _OUTPUT0_alter = %nrquote(ALTER=&alterpass.);
%let _OUTPUT0_path = %nrquote(/dw_solution/mel/data/resu/mel_resu.ECL_LLG%(Table%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote(ECL loan, limit and guarantee);
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date account_id account_number_official bank_id 
        type_of_run_cd owner1_ssn_id owner1_name result_office_id portfolio_cd 
        account_type_cd booked_balance_amt currency_cd ecl_amt ecl_euro_amt 
        ecl_sek_min_lvl_amt ecl_euro_min_lvl_amt 
        ecl_euro_min_lvl_on_balance_amt ecl_euro_min_lvl_off_balance_amt 
        ecl_sek_min_lvl_on_balance_amt ecl_sek_min_lvl_off_balance_amt 
        ead_future_1 ead_future_1_sek ead_future_1_euro lgd_future_1 
        pd_actual_12m pd_initial_12m pd_actual_lifetime pd_initial_lifetime 
        pd_actual_future_1 stage stage_previous waiting_period 
        waiting_period_previous proposed_stage default_flg 
        forbearance_status_cd overdraft_days_cnt unmanaged_days_cnt 
        low_credit_risk_flg calculated_end_date lgd_group ecl_override_flg 
        initial_date loaded_dt;


%let dimfields = ;
%let dimfields_count = 0;
%let dimfields0 = 0;
%let dimfields = ;

/* List of target columns to keep  */ 
%let _keep = information_date account_id account_number_official bank_id 
        type_of_run_cd owner1_ssn_id owner1_name result_office_id portfolio_cd 
        account_type_cd booked_balance_amt currency_cd ecl_amt ecl_euro_amt 
        ecl_sek_min_lvl_amt ecl_euro_min_lvl_amt 
        ecl_euro_min_lvl_on_balance_amt ecl_euro_min_lvl_off_balance_amt 
        ecl_sek_min_lvl_on_balance_amt ecl_sek_min_lvl_off_balance_amt 
        ead_future_1 ead_future_1_sek ead_future_1_euro lgd_future_1 
        pd_actual_12m pd_initial_12m pd_actual_lifetime pd_initial_lifetime 
        pd_actual_future_1 stage stage_previous waiting_period 
        waiting_period_previous proposed_stage default_flg 
        forbearance_status_cd overdraft_days_cnt unmanaged_days_cnt 
        low_credit_risk_flg calculated_end_date lgd_group ecl_override_flg 
        initial_date loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date account_id account_number_official bank_id 
        type_of_run_cd owner1_ssn_id owner1_name result_office_id portfolio_cd 
        account_type_cd booked_balance_amt currency_cd ecl_amt ecl_euro_amt 
        ecl_sek_min_lvl_amt ecl_euro_min_lvl_amt 
        ecl_euro_min_lvl_on_balance_amt ecl_euro_min_lvl_off_balance_amt 
        ecl_sek_min_lvl_on_balance_amt ecl_sek_min_lvl_off_balance_amt 
        ead_future_1 ead_future_1_sek ead_future_1_euro lgd_future_1 
        pd_actual_12m pd_initial_12m pd_actual_lifetime pd_initial_lifetime 
        pd_actual_future_1 stage stage_previous waiting_period 
        waiting_period_previous proposed_stage default_flg 
        forbearance_status_cd overdraft_days_cnt unmanaged_days_cnt 
        low_credit_risk_flg calculated_end_date lgd_group ecl_override_flg 
        initial_date loaded_dt;
%history(source=&_INPUT0.,target=&_OUTPUT0.,metapath=&_OUTPUT0_path.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

/*---- Create the indexes for a table  ----*/ 
%put %str(NOTE: Creating indexes ...);
proc datasets lib = mel_resu nolist; 
   modify ECL_LLG(ALTER=&alterpass. ); 
      index create primary_index = (information_date account_id bank_id type_of_run_cd)
         / unique;
quit; 

%rcSet(&syserr); 



/**  Step end history **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/*---- Start of Post-Process Code  ----*/ 

%postprocess_std;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

